#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 07 15:39:41 CEST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6df6b375878f426d9eb7540d0942bfa6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot compt_sync_behav xil_defaultlib.compt_sync -log elaborate.log"
xelab -wto 6df6b375878f426d9eb7540d0942bfa6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot compt_sync_behav xil_defaultlib.compt_sync -log elaborate.log

