webtalk_init -webtalk_dir /volsme/user1x/users/mi01a014/Bureau/TP1/TP1.sim/sim_1/behav/xsim/xsim.dir/add2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 30 16:17:48 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3aef7d1d-d00e-42b9-a8eb-54b8a6dd281b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9fe297bf8f3143df8dee5f501037db94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.9 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4360 CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3234.412 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "80 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1844540349 -regid "" -xml /volsme/user1x/users/mi01a014/Bureau/TP1/TP1.sim/sim_1/behav/xsim/xsim.dir/add2_behav/webtalk/usage_statistics_ext_xsim.xml -html /volsme/user1x/users/mi01a014/Bureau/TP1/TP1.sim/sim_1/behav/xsim/xsim.dir/add2_behav/webtalk/usage_statistics_ext_xsim.html -wdm /volsme/user1x/users/mi01a014/Bureau/TP1/TP1.sim/sim_1/behav/xsim/xsim.dir/add2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
